# Generated by Django 6.0.3 on 2026-03-28 20:34
"""
dcs
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    dcs
    """
    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='commentary',
            field=models.CharField(default='', max_length=300),
        ),
    ]
