# Generated by Django 6.0.3 on 2026-04-04 10:12
"""
dcs
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    dcs
    """
    dependencies = [
        ('mainapp', '0002_problem_commentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='left_border',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='right_border',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
